### ISSUE TITLE
Is there a way to remove the H1 symbol along with headings

### ISSUE THREAD

**Issue by jayprog884** [bcdavasconcelos/Obsidian-GDCT#1]
![image](https://user-images.githubusercontent.com/75081068/106710249-a5fe7900-661b-11eb-87f5-2eb9c22d71ab.png)

**Comment by bcdavasconcelos** [comment]
Hi. Yes, there is. Just look for 'H1' in the CSS file and delete it. 

I will close this, but if you have other questions, feel free to ask.
